import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    alignItems: 'center',
    paddingVertical: 32,
    paddingHorizontal: 12,
    backgroundColor: '#fff',
  },
  scanButton: {
    backgroundColor: '#F7A800',
    borderRadius: 8,
    paddingVertical: 16,
    paddingHorizontal: 32,
    marginTop: 24,
    marginBottom: 12,
    minWidth: 220,
    alignItems: 'center',
  },
  scanButtonText: {
    color: '#222',
    fontWeight: 'bold',
    fontSize: 18,
  },
  orText: {
    fontSize: 16,
    color: '#888',
    marginVertical: 12,
    fontWeight: 'bold',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 16,
    marginTop: 8,
  },
  coolDropdown: {
    marginBottom: 16,
    minWidth: 320,
    maxWidth: 420,
    width: '90%',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ccc',
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 17,
  },
  coolDropdownContainer: {
    borderRadius: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ccc',
  },
  coolDropdownPlaceholder: {
    color: '#888',
    fontSize: 16,
    fontWeight: '400',
  },
  coolDropdownSelectedText: {
    color: '#222',
    fontSize: 17,
    fontWeight: '500',
  },
  coolDropdownItemText: {
    color: '#222',
    fontSize: 16,
  },
  coolDropdownIcon: {
    width: 24,
    height: 24,
    tintColor: '#888',
  },
  submitButton: {
    backgroundColor: '#F7A800',
    borderRadius: 8,
    paddingVertical: 16,
    paddingHorizontal: 32,
    minWidth: 140,
    maxWidth: 160,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  submitButtonText: {
    color: '#222',
    fontWeight: 'bold',
    fontSize: 16,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
    width: '100%',
    paddingHorizontal: 20,
  },
  clearButton: {
    backgroundColor: '#F7A800',
    borderRadius: 8,
    paddingVertical: 16,
    paddingHorizontal: 24,
    minWidth: 160,
    maxWidth: 180,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  clearButtonText: {
    color: '#222',
    fontWeight: 'bold',
    fontSize: 16,
  },
});

export const networkMapStyles = {
  container: {
    flexGrow: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 20,
  },
  pathContainer: {
    backgroundColor: '#111',
    borderRadius: 16,
    padding: 18,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
  },
  pathRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  icon: {
    marginRight: 12,
  },
  pathText: {
    color: '#fff',
    fontSize: 14,
    marginBottom: 4,
  },
}; 